# docker version  >> write to file docker-compose.yml
version: "3"

services:  
  Keycloak_svr:    
    image: quay.io/keycloak/keycloak:latest      
    command: start-dev
    environment:      
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_kc_svr
      KC_DB_URL_DATABASE: db_keycloak
      KC_DB_PASSWORD: root
      KC_DB_USERNAME: root
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin      
    ports:      
      - "8147:8080"      
    depends_on:      
      postgres_kc_svr:
        condition: service_healthy
    networks:
      network_sso:
        ipv4_address: "10.0.0.2"    
    volumes:
      - ./realms/:/opt/keycloak/data/import/

  postgres_kc_svr: 
    image: postgres:latest
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'    
    environment:
      # Environment Variables expecially for Postgres
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: "exit 0"
    ports:
      - "7432:5432"
    networks:
      network_sso:
        ipv4_address: "10.0.0.3"
    volumes:
      - ./backup_db.sql:/docker-entrypoint-initdb.d/my_db.sql
networks:  
  network_sso:
    ipam:
    # IP Address management
      driver: default
      # default = bridge
      config:
        - subnet: "10.0.0.0/24"